### Request this and then try to commit a change to github
GET http://haltalk.herokuapp.com/
Accept: application/hal+json

### Request this and then try to commit a change to github
GET http://haltalk.herokuapp.com/
Accept: application/json
